"""A1 landscape title-block layout constants."""

from pptx.dml.color import RGBColor
from pptx.util import Pt

SLIDE_W_MM = 841.0
SLIDE_H_MM = 594.0

BLACK = RGBColor(0x1F, 0x29, 0x37)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
DARK_GREY = RGBColor(0x37, 0x41, 0x51)
MID_GREY = RGBColor(0x6B, 0x72, 0x80)
LIGHT_GREY = RGBColor(0xE5, 0xE7, 0xEB)
ACCENT_BLUE = RGBColor(0x0F, 0x76, 0xC7)

MARGIN = 7.0
INNER_MARGIN = 13.0
TITLEBLOCK_H = 55.0
TITLEBLOCK_TOP = SLIDE_H_MM - INNER_MARGIN - TITLEBLOCK_H

CONTENT_L = INNER_MARGIN
CONTENT_T = INNER_MARGIN
CONTENT_R = SLIDE_W_MM - INNER_MARGIN
CONTENT_B = TITLEBLOCK_TOP
CONTENT_W = CONTENT_R - CONTENT_L
CONTENT_H = CONTENT_B - CONTENT_T

FS_LABEL = Pt(6.0)
FS_VALUE = Pt(8.5)
FS_TITLE = Pt(13.0)
FS_PROJECT = Pt(11.0)
